import {supabase} from '../lib/supabase';
import type {Event,MarketSnapshot,Prediction,Profile,ProfileSummary,RankingEntry,RatingRecord} from '../types';
const ok=(e:any)=>{if(e)throw e};
export async function getMyProfile(userId:string):Promise<ProfileSummary>{const[{data:p,error:pe},{count:fr},{count:fg},{count:pc},{data:rs,error:re}]=await Promise.all([supabase.from('profiles').select('*').eq('id',userId).single(),supabase.from('follows').select('*',{count:'exact',head:true}).eq('followed_id',userId),supabase.from('follows').select('*',{count:'exact',head:true}).eq('follower_id',userId),supabase.from('predictions').select('*',{count:'exact',head:true}).eq('user_id',userId),supabase.from('ratings').select('*').eq('user_id',userId)]);ok(pe);ok(re);const r=(rs??[]) as RatingRecord[];return{profile:p as Profile,overall_rating:r.find(x=>x.scope_type==='overall')??null,specializations:r.filter(x=>x.scope_type!=='overall'),followers_count:fr??0,following_count:fg??0,predictions_count:pc??0}}
export async function updateMyProfile(userId:string,patch:any){const{data,error}=await supabase.from('profiles').update(patch).eq('id',userId).select('*').single();ok(error);return data as Profile}
export async function listUpcomingEvents():Promise<Event[]>{const{data,error}=await supabase.from('events').select('*, competition:competitions(*)').gte('kickoff_at',new Date().toISOString()).order('kickoff_at').limit(40);ok(error);return(data??[]) as Event[]}
export async function listLatestMarkets(ids:string[]):Promise<MarketSnapshot[]>{if(!ids.length)return[];const{data,error}=await supabase.from('markets').select('*').in('event_id',ids).order('captured_at',{ascending:false});ok(error);const seen=new Set<string>();return((data??[]) as MarketSnapshot[]).filter(x=>{const k=`${x.event_id}|${x.market_type}|${x.selection}`;if(seen.has(k))return false;seen.add(k);return true})}
export async function listFeed(userId:string):Promise<Prediction[]>{const{data:blocked}=await supabase.from('blocks').select('blocked_id').eq('blocker_id',userId);const b=new Set((blocked??[]).map(x=>x.blocked_id));const{data,error}=await supabase.from('predictions').select('*').order('created_at',{ascending:false}).limit(50);ok(error);const raw=((data??[]) as Prediction[]).filter(x=>!b.has(x.user_id));const u=[...new Set(raw.map(x=>x.user_id))],e=[...new Set(raw.map(x=>x.event_id))],p=raw.map(x=>x.id);const[{data:ps},{data:es},{data:rs},{data:ls},{data:cs},{data:ml}]=await Promise.all([u.length?supabase.from('profiles').select('*').in('id',u):Promise.resolve({data:[]}),e.length?supabase.from('events').select('*, competition:competitions(*)').in('id',e):Promise.resolve({data:[]}),u.length?supabase.from('ratings').select('*').in('user_id',u).eq('scope_type','overall'):Promise.resolve({data:[]}),p.length?supabase.from('prediction_likes').select('prediction_id').in('prediction_id',p):Promise.resolve({data:[]}),p.length?supabase.from('comments').select('prediction_id').in('prediction_id',p).is('deleted_at',null):Promise.resolve({data:[]}),p.length?supabase.from('prediction_likes').select('prediction_id').eq('user_id',userId).in('prediction_id',p):Promise.resolve({data:[]})]);const pm=new Map((ps??[]).map((x:any)=>[x.id,x])),em=new Map((es??[]).map((x:any)=>[x.id,x])),rm=new Map((rs??[]).map((x:any)=>[x.user_id,x])),lc=new Map<string,number>(),cc=new Map<string,number>(),mine=new Set((ml??[]).map((x:any)=>x.prediction_id));for(const x of ls??[])lc.set(x.prediction_id,(lc.get(x.prediction_id)??0)+1);for(const x of cs??[])cc.set(x.prediction_id,(cc.get(x.prediction_id)??0)+1);return raw.map(x=>({...x,profile:pm.get(x.user_id),event:em.get(x.event_id),overall_rating:rm.get(x.user_id),likes_count:lc.get(x.id)??0,comments_count:cc.get(x.id)??0,liked_by_me:mine.has(x.id)}))}
export async function listEventPredictions(eventId:string):Promise<Prediction[]>{const{data,error}=await supabase.from('predictions').select('*').eq('event_id',eventId).order('created_at',{ascending:false});ok(error);const raw=(data??[]) as Prediction[],u=[...new Set(raw.map(x=>x.user_id))];const[{data:ps},{data:rs}]=await Promise.all([u.length?supabase.from('profiles').select('*').in('id',u):Promise.resolve({data:[]}),u.length?supabase.from('ratings').select('*').in('user_id',u).eq('scope_type','overall'):Promise.resolve({data:[]})]);const pm=new Map((ps??[]).map((x:any)=>[x.id,x])),rm=new Map((rs??[]).map((x:any)=>[x.user_id,x]));return raw.map(x=>({...x,profile:pm.get(x.user_id),overall_rating:rm.get(x.user_id)}))}
export async function createPredictionFromMarket(x:{marketId:string;confidence:number;units:number;analysis?:string}){const{data,error}=await supabase.rpc('create_prediction_from_market',{p_market_id:x.marketId,p_confidence:x.confidence,p_units:x.units,p_analysis:x.analysis?.trim()||null});ok(error);return data as string}
export async function togglePredictionLike(userId:string,predictionId:string,liked:boolean){const q=liked?supabase.from('prediction_likes').delete().eq('user_id',userId).eq('prediction_id',predictionId):supabase.from('prediction_likes').insert({user_id:userId,prediction_id:predictionId});const{error}=await q;ok(error)}
export async function addComment(userId:string,predictionId:string,body:string){const{error}=await supabase.from('comments').insert({user_id:userId,prediction_id:predictionId,body:body.trim()});ok(error)}
export async function followProfile(userId:string,targetId:string,follow:boolean){const q=follow?supabase.from('follows').insert({follower_id:userId,followed_id:targetId}):supabase.from('follows').delete().eq('follower_id',userId).eq('followed_id',targetId);const{error}=await q;ok(error)}
export async function reportPrediction(userId:string,predictionId:string,reason:string){const{error}=await supabase.from('reports').insert({reporter_id:userId,target_type:'prediction',target_id:predictionId,reason});ok(error)}
export async function listFollowingIds(userId:string){const{data,error}=await supabase.from('follows').select('followed_id').eq('follower_id',userId);ok(error);return(data??[]).map(x=>x.followed_id as string)}
export async function listRankings():Promise<RankingEntry[]>{const{data,error}=await supabase.from('ratings').select('*').eq('scope_type','overall').eq('scope_key','all').gte('sample_size',20).order('rating',{ascending:false}).limit(100);ok(error);const r=(data??[]) as RatingRecord[],ids=r.map(x=>x.user_id);if(!ids.length)return[];const[{data:ps},{data:fs}]=await Promise.all([supabase.from('profiles').select('*').in('id',ids),supabase.from('follows').select('followed_id').in('followed_id',ids)]);const pm=new Map((ps??[]).map((x:any)=>[x.id,x as Profile])),fm=new Map<string,number>();for(const x of fs??[])fm.set(x.followed_id,(fm.get(x.followed_id)??0)+1);return r.filter(x=>pm.has(x.user_id)).map(x=>({profile:pm.get(x.user_id)!,rating:x,followers_count:fm.get(x.user_id)??0}))}
